require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HttpRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # HttpRequest. As you add validations to HttpRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "method" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HttpRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all http_requests as @http_requests" do
      http_request = HttpRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:http_requests).should eq([http_request])
    end
  end

  describe "GET show" do
    it "assigns the requested http_request as @http_request" do
      http_request = HttpRequest.create! valid_attributes
      get :show, {:id => http_request.to_param}, valid_session
      assigns(:http_request).should eq(http_request)
    end
  end

  describe "GET new" do
    it "assigns a new http_request as @http_request" do
      get :new, {}, valid_session
      assigns(:http_request).should be_a_new(HttpRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested http_request as @http_request" do
      http_request = HttpRequest.create! valid_attributes
      get :edit, {:id => http_request.to_param}, valid_session
      assigns(:http_request).should eq(http_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HttpRequest" do
        expect {
          post :create, {:http_request => valid_attributes}, valid_session
        }.to change(HttpRequest, :count).by(1)
      end

      it "assigns a newly created http_request as @http_request" do
        post :create, {:http_request => valid_attributes}, valid_session
        assigns(:http_request).should be_a(HttpRequest)
        assigns(:http_request).should be_persisted
      end

      it "redirects to the created http_request" do
        post :create, {:http_request => valid_attributes}, valid_session
        response.should redirect_to(HttpRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved http_request as @http_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        HttpRequest.any_instance.stub(:save).and_return(false)
        post :create, {:http_request => { "method" => "invalid value" }}, valid_session
        assigns(:http_request).should be_a_new(HttpRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HttpRequest.any_instance.stub(:save).and_return(false)
        post :create, {:http_request => { "method" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested http_request" do
        http_request = HttpRequest.create! valid_attributes
        # Assuming there are no other http_requests in the database, this
        # specifies that the HttpRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HttpRequest.any_instance.should_receive(:update).with({ "method" => "MyString" })
        put :update, {:id => http_request.to_param, :http_request => { "method" => "MyString" }}, valid_session
      end

      it "assigns the requested http_request as @http_request" do
        http_request = HttpRequest.create! valid_attributes
        put :update, {:id => http_request.to_param, :http_request => valid_attributes}, valid_session
        assigns(:http_request).should eq(http_request)
      end

      it "redirects to the http_request" do
        http_request = HttpRequest.create! valid_attributes
        put :update, {:id => http_request.to_param, :http_request => valid_attributes}, valid_session
        response.should redirect_to(http_request)
      end
    end

    describe "with invalid params" do
      it "assigns the http_request as @http_request" do
        http_request = HttpRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HttpRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => http_request.to_param, :http_request => { "method" => "invalid value" }}, valid_session
        assigns(:http_request).should eq(http_request)
      end

      it "re-renders the 'edit' template" do
        http_request = HttpRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HttpRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => http_request.to_param, :http_request => { "method" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested http_request" do
      http_request = HttpRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => http_request.to_param}, valid_session
      }.to change(HttpRequest, :count).by(-1)
    end

    it "redirects to the http_requests list" do
      http_request = HttpRequest.create! valid_attributes
      delete :destroy, {:id => http_request.to_param}, valid_session
      response.should redirect_to(http_requests_url)
    end
  end

end
